development:
  adapter: postgresql
  encoding: utf8
  database: sauce_api_development
  pool: 5
  username: postgres
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sauce_api_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: utf8
  host: ec2-107-20-217-22.compute-1.amazonaws.com
  database: devska45m3l4ae
  pool: 5
  username: qilqyxxdpovezr
  password: ENV["HEROKU_DB_PASSWORD"]
